/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.siu.application;

import com.siu.DAO.DICHVU_DAO;
import com.siu.model.CHITIETMUON;
import com.siu.model.PHAT;
import com.siu.model.PHIEUMUON;
import com.siu.model.TRASACH;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicTabbedPaneUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class Bao_cao extends javax.swing.JFrame {

    /**
     * Creates new form Bao_cao
     */
    private String msnvDN;

    public Bao_cao() throws Exception {
        initComponents();
        tblPhieuTra.setDefaultEditor(Object.class, null);
        tblPhieuPhat.setDefaultEditor(Object.class, null);
        loadAllData();
      
    }

    public Bao_cao(String msnvDN) throws Exception {

        initComponents();
        loadAllData();
        this.msnvDN = msnvDN;

    }

    // nếu code khác cần đọc
    
    private void warn(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Warning", JOptionPane.WARNING_MESSAGE);
    }

    public String getMsnvDN() {
        return msnvDN;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhieuMuon = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btnTraSach = new javax.swing.JButton();
        btnTKPM = new javax.swing.JButton();
        btnXoaPM = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPhieuTra = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnTKPT = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPhieuPhat = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        btnTKPP = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dịch Vụ");
        setMinimumSize(new java.awt.Dimension(735, 630));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        tblPhieuMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã số phiếu mượn", "MSDG", "MSNV", "Mã bản sao", "Ngày mượn", "Hạn trả", "Trạng Thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPhieuMuon.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblPhieuMuon);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 177, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        btnTraSach.setBackground(new java.awt.Color(51, 153, 255));
        btnTraSach.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTraSach.setForeground(new java.awt.Color(255, 255, 255));
        btnTraSach.setText("Trả sách");
        btnTraSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraSachActionPerformed(evt);
            }
        });

        btnTKPM.setBackground(new java.awt.Color(51, 153, 255));
        btnTKPM.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTKPM.setForeground(new java.awt.Color(255, 255, 255));
        btnTKPM.setText("Tìm kiếm");
        btnTKPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKPMActionPerformed(evt);
            }
        });

        btnXoaPM.setBackground(new java.awt.Color(51, 153, 255));
        btnXoaPM.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXoaPM.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaPM.setText("Xóa");
        btnXoaPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaPMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTraSach, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTKPM, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoaPM, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTraSach, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTKPM, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnXoaPM, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Danh sách phiếu mượn", jPanel1);

        tblPhieuTra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã số phiếu mượn", "Mã bản sao", "MSNV", "Ngày trả"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblPhieuTra);

        btnTKPT.setBackground(new java.awt.Color(51, 153, 255));
        btnTKPT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTKPT.setForeground(new java.awt.Color(255, 255, 255));
        btnTKPT.setText("Tìm Kiếm");
        btnTKPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKPTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnTKPT, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btnTKPT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Danh sách phiếu trả", jPanel2);

        tblPhieuPhat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã số phiếu phạt", "Mã số phiếu mượn", "Mã bản sao", "MSNV", "Ngày phạt", "Lí do phạt"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblPhieuPhat);

        btnTKPP.setBackground(new java.awt.Color(51, 153, 255));
        btnTKPP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTKPP.setForeground(new java.awt.Color(255, 255, 255));
        btnTKPP.setText("Tìm Kiếm");
        btnTKPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKPPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnTKPP, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(btnTKPP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Danh sách phiếu phạt", jPanel3);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ptit/icon/Graphicrating-Koloria-Button-Back.32.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Thêm các phương thức load dữ liệu và xử lý sự kiện
    private void loadTablePhieuMuon() throws Exception {
        DICHVU_DAO PM_dao = new DICHVU_DAO();
        ArrayList<PHIEUMUON> lst_PM = new ArrayList<>();
        DefaultTableModel model = (DefaultTableModel) tblPhieuMuon.getModel();
        model.setRowCount(0); // xóa dữ liệu cũ
        model.setColumnIdentifiers(new Object[]{
            "Mã số phiếu mượn", "MSDG", "MSNV", "Mã bản sao", "Ngày mượn", "Hạn trả", "Trạng thái"
        });
        lst_PM = PM_dao.getDSPM();
        // Định dạng ngày
        for (PHIEUMUON pm : lst_PM) {
            PM_dao.updateTrangThaiQuaHan(pm.getSoPhieuMuon());
        }
        lst_PM = PM_dao.getDSPM();
        SimpleDateFormat dinhDang = new SimpleDateFormat("dd/MM/yyyy");

        for (PHIEUMUON pm : lst_PM) {
            String[] data = {
                pm.getSoPhieuMuon(),
                pm.getMSDG(),
                pm.getMSNV(),
                getMaBanSaoFromCTM(pm.getSoPhieuMuon()), // Lấy mã bản sao từ chi tiết mượn
                dinhDang.format(pm.getNgayMuon()),
                dinhDang.format(pm.getHanTra()),
                pm.getTrangThai()
            };
            System.out.println(pm);
            model.addRow(data);
        }
        tblPhieuMuon.setModel(model);
    }

    private void loadTablePhieuTra() {
        try {
            DICHVU_DAO dao = new DICHVU_DAO();
            ArrayList<TRASACH> list = dao.getDSPT(); // Cần thêm phương thức này trong DAO
            DefaultTableModel model = (DefaultTableModel) tblPhieuTra.getModel();
            model.setRowCount(0);

            for (TRASACH ts : list) {
                model.addRow(new Object[]{
                    ts.getSoPhieuMuon(),
                    ts.getMaBanSao(),
                    ts.getMsnv(),
                    ts.getNgayTra()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi tải dữ liệu phiếu trả: " + e.getMessage());
        }
    }

    private void loadTablePhieuPhat() {
        try {
            DICHVU_DAO dao = new DICHVU_DAO();
            ArrayList<PHAT> list = dao.getDSPP();
            DefaultTableModel model = (DefaultTableModel) tblPhieuPhat.getModel();
            model.setRowCount(0);

            for (PHAT pp : list) {
                model.addRow(new Object[]{
                    pp.getSoPhieuPhat(),
                    pp.getSoPhieuMuon(),
                    pp.getMaBanSao(),
                    pp.getMsnv(),
                    pp.getNgayPhat(),
                    pp.getLyDoPhat()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi tải dữ liệu phiếu phạt: " + e.getMessage());
        }
    }

// Phương thức lấy mã bản sao từ chi tiết mượn
    private String getMaBanSaoFromCTM(String soPhieuMuon) {
        try {
            DICHVU_DAO dao = new DICHVU_DAO();
            ArrayList<String> list = dao.getLstMBS_chiTiet(soPhieuMuon);
            if (list != null && !list.isEmpty()) {
                // Lấy tất cả mã bản sao, ngăn cách bằng dấu phẩy nếu có nhiều
                StringBuilder maBanSaos = new StringBuilder();
                for (String ctm : list) {
                    if (maBanSaos.length() > 0) {
                        maBanSaos.append(", ");
                    }
                    maBanSaos.append(ctm);
                }
                return maBanSaos.toString();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return "";
    }

// Thêm phương thức khởi tạo dữ liệu khi form được hiển thị
    public void loadAllData() throws Exception {
        loadTablePhieuMuon();
        loadTablePhieuTra();
        loadTablePhieuPhat();
    }

// Xử lý sự kiện cho các button

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
//        Menu menu = new Menu(msnvDN);
//        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnTraSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraSachActionPerformed

       int selectedRow = tblPhieuMuon.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui long chon 1 dong!");
            return;
        }
        DICHVU_DAO dao = new DICHVU_DAO();

        String spm = tblPhieuMuon.getValueAt(selectedRow, 0).toString();
        String trangThai = tblPhieuMuon.getValueAt(selectedRow, 5).toString();
        if (spm.trim().isEmpty()) {
            warn("So phieu muon khong duoc de trong!");
            return;
        }
        if (getMsnvDN().trim().isEmpty() || getMsnvDN() == null) {
            warn("Ma so nhan vien khong duoc de trong!");
            return;
        }
        if (trangThai.equalsIgnoreCase("Da tra") || trangThai.equalsIgnoreCase("Bi phat")) {
            warn("Phieu muon da duoc tra!");
            return;
        }

        try {
            String mess = dao.traSach(spm, getMsnvDN());
            JOptionPane.showMessageDialog(this, mess);
        } catch (Exception ex) {
            Logger.getLogger(Bao_cao.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            loadTablePhieuMuon();
        } catch (Exception ex) {
            Logger.getLogger(Bao_cao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTraSachActionPerformed

    private void btnTKPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKPPActionPerformed
        String spp = JOptionPane.showInputDialog(this, "Nhap so phieu phat: ", "Tim kiem", JOptionPane.QUESTION_MESSAGE);

        DefaultTableModel model = (DefaultTableModel) tblPhieuPhat.getModel();

        if (spp == null || spp.trim().isEmpty()) {
            return; // thoát không làm gì
        }

        boolean found = false;
        for (int i = 0; i < model.getRowCount(); i++) {
            String value = model.getValueAt(i, 0).toString();
            if (value.equalsIgnoreCase(spp.trim())) {
                // Chọn dòng và cuộn đến đó
                tblPhieuPhat.setRowSelectionInterval(i, i);
                tblPhieuPhat.scrollRectToVisible(tblPhieuPhat.getCellRect(i, 0, true));
                found = true;
                break;
            }
        }

        if (!found) {
            JOptionPane.showMessageDialog(this, "Khong tim thay phieu phat co ma: " + spp, "Ket qua", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnTKPPActionPerformed

    private void btnTKPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKPMActionPerformed
        // TODO add your handling code here:
         String spm = JOptionPane.showInputDialog(this, "Nhap so phieu muon: ", "Tim kiem", JOptionPane.QUESTION_MESSAGE);

        DefaultTableModel model = (DefaultTableModel) tblPhieuMuon.getModel();

        if (spm == null || spm.trim().isEmpty()) {
            return; // thoát không làm gì
        }

        boolean found = false;
        for (int i = 0; i < model.getRowCount(); i++) {
            String value = model.getValueAt(i, 0).toString();
            if (value.equalsIgnoreCase(spm.trim())) {
                // Chọn dòng và cuộn đến đó
                tblPhieuMuon.setRowSelectionInterval(i, i);
                tblPhieuMuon.scrollRectToVisible(tblPhieuMuon.getCellRect(i, 0, true));
                found = true;
                break;
            }
        }

        if (!found) {
            JOptionPane.showMessageDialog(this, "Khong tim thay phieu muon co ma: " + spm, "Ket qua", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnTKPMActionPerformed

    private void btnXoaPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaPMActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblPhieuMuon.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui long chon 1 dong!");
            return;
        }
        String trangThai = tblPhieuMuon.getValueAt(selectedRow, 6).toString().trim();
        if (trangThai.equalsIgnoreCase("Dang muon") || trangThai.equalsIgnoreCase("Qua han")) {
            warn("Tra sach truoc khi xoa");
            return;
        }

        Object[] options = {"Yes", "No"};

        int choice = JOptionPane.showOptionDialog(this, "Ban co muon xoa khong", "Xoa du lieu", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]);

        if (choice == JOptionPane.YES_OPTION) {
            DICHVU_DAO dao = new DICHVU_DAO();
            String spm = tblPhieuMuon.getValueAt(selectedRow, 0).toString();
            try {
                String mess = dao.xoaPhieuMuon(spm);
                JOptionPane.showMessageDialog(this, mess);
            } catch (Exception ex) {
                Logger.getLogger(Bao_cao.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                loadTablePhieuMuon();
            } catch (Exception ex) {
                Logger.getLogger(Bao_cao.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnXoaPMActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            int selectedIndex = jTabbedPane1.getSelectedIndex();

            switch (selectedIndex) {
                case 0:
                    loadTablePhieuMuon();
                    break;
                case 1:
                    loadTablePhieuTra();
                    break;
                case 2:
                    loadTablePhieuPhat();
                    break;

            }
        } catch (Exception ex) {
            Logger.getLogger(Bao_cao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void btnTKPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKPTActionPerformed
        // TODO add your handling code here:
        String spm = JOptionPane.showInputDialog(this, "Nhap so phieu muon: ", "Tim kiem", JOptionPane.QUESTION_MESSAGE);

        DefaultTableModel model = (DefaultTableModel) tblPhieuTra.getModel();

        if (spm == null || spm.trim().isEmpty()) {
            return; // thoát không làm gì
        }

        tblPhieuTra.clearSelection(); // Xóa chọn cũ
        boolean found = false;

        for (int i = 0; i < model.getRowCount(); i++) {
            String value = model.getValueAt(i, 0).toString();
            if (value.equalsIgnoreCase(spm.trim())) {
                // Chọn nhiều dòng cùng lúc
                tblPhieuTra.addRowSelectionInterval(i, i);
                found = true;
            }
        }

// Nếu muốn cuộn đến dòng đầu tiên tìm thấy
        if (found) {
            int firstIndex = tblPhieuTra.getSelectedRows()[0];
            tblPhieuTra.scrollRectToVisible(tblPhieuTra.getCellRect(firstIndex, 0, true));
        }

        if (!found) {
            JOptionPane.showMessageDialog(this, "Khong tim thay phieu muon co ma: " + spm, "Ket qua", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnTKPTActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        Menu menu = new Menu(msnvDN);
        menu.setVisible(true);
        menu.setLocationRelativeTo(this);
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bao_cao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bao_cao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bao_cao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bao_cao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Bao_cao("test").setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Bao_cao.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnTKPM;
    private javax.swing.JButton btnTKPP;
    private javax.swing.JButton btnTKPT;
    private javax.swing.JButton btnTraSach;
    private javax.swing.JButton btnXoaPM;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblPhieuMuon;
    private javax.swing.JTable tblPhieuPhat;
    private javax.swing.JTable tblPhieuTra;
    // End of variables declaration//GEN-END:variables
}
