/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.siu.application;

import com.siu.DAO.BAN_SAO_DAO;
import com.siu.DAO.DAU_SACH_DAO;
import com.siu.DAO.LOAI_SACH_DAO;
import com.siu.DAO.NHA_XUAT_BAN_DAO;
import com.siu.DAO.TAC_GIA_DAO;
import com.siu.model.BAN_SAO;
import com.siu.model.DAU_SACH;
import com.siu.model.LOAI_SACH;
import com.siu.model.NHA_XUAT_BAN;
import com.siu.model.TAC_GIA;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class Chi_tiet_sach extends javax.swing.JFrame {

    /**
     * Creates new form Chi_tiet_sach
     */
    public Chi_tiet_sach() {
        initComponents();
    }

    private LOAI_SACH_DAO loaiSachDao = new LOAI_SACH_DAO();
    private BAN_SAO_DAO banSaoDao = new BAN_SAO_DAO();
    private TAC_GIA_DAO tacGiaDao = new TAC_GIA_DAO();
    private NHA_XUAT_BAN_DAO nxbDao = new NHA_XUAT_BAN_DAO();
    private DAU_SACH_DAO dauSachDao = new DAU_SACH_DAO();

    public Chi_tiet_sach(String maDauSach, String maTacGia, String msNXB, String maLoaiSach) {
        initComponents();
        loadLoaiSach(maLoaiSach);
        loadBanSao(maDauSach);
        loadTacGia(maTacGia);
        loadNXB(msNXB);
    }

    private void loadLoaiSach(String maLoai) {
        try {
            List<LOAI_SACH> list = loaiSachDao.getByMaLoai(maLoai);
            DefaultTableModel model = (DefaultTableModel) tblLoaiSach.getModel();
            model.setRowCount(0);

            for (LOAI_SACH ls : list) {
                model.addRow(new Object[]{
                    ls.getMaLoaiSach(),
                    ls.getTenLoai()
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadBanSao(String maDauSach) {
        try {
            List<BAN_SAO> list = banSaoDao.getByMaDauSach(maDauSach);
            DefaultTableModel model = (DefaultTableModel) tblBanSao.getModel();
            model.setRowCount(0);

            for (BAN_SAO bs : list) {
                model.addRow(new Object[]{
                    bs.getMaBanSao(),
                    bs.getMaDauSach(),
                    bs.getTinhTrang(),
                    bs.getViTri()
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadTacGia(String maTacGia) {
        try {
            TAC_GIA tg = tacGiaDao.getByMaTacGia(maTacGia);
            DefaultTableModel model = (DefaultTableModel) tblTacGia.getModel();
            model.setRowCount(0);

            DAU_SACH ds = dauSachDao.getByMaTacGia(maTacGia);
            if (tg != null) {
                model.addRow(new Object[]{
                    ds.getMaDauSach(),
                    tg.getMaTacGia(),
                    tg.getTenTacGia()
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadNXB(String ms) {
        try {
            NHA_XUAT_BAN nxb = nxbDao.getByMS(ms);
            DefaultTableModel model = (DefaultTableModel) tblNXB.getModel();
            model.setRowCount(0);

            if (nxb != null) {
                model.addRow(new Object[]{
                    nxb.getmSNXB(),
                    nxb.getTenNXB(),
                    nxb.getDiaChiNXB(),
                    nxb.getWebsiteNXB(),
                    nxb.getThongTinKhac()
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLoaiSach = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblBanSao = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblTacGia = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblNXB = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chi tiết sách");

        tblLoaiSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã loại sách", "Tên loại"
            }
        ));
        jScrollPane2.setViewportView(tblLoaiSach);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Chi tiết loại sách", jPanel2);

        tblBanSao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã bản sao", "Mã đầu sách", "Tình trạng", "Vị trí"
            }
        ));
        jScrollPane3.setViewportView(tblBanSao);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Chi tiết bản sao", jPanel3);

        tblTacGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã đầu sách", "Mã tác giả", "Tên tác giả"
            }
        ));
        jScrollPane4.setViewportView(tblTacGia);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Chi tiết tác giả", jPanel4);

        tblNXB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã số NXB", "Tên NXB", "Địa chỉ NXB", "Website NXB", "Thông tin khác"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblNXB);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Chi tiết nhà xuất bản", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chi_tiet_sach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chi_tiet_sach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chi_tiet_sach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chi_tiet_sach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chi_tiet_sach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblBanSao;
    private javax.swing.JTable tblLoaiSach;
    private javax.swing.JTable tblNXB;
    private javax.swing.JTable tblTacGia;
    // End of variables declaration//GEN-END:variables
}
