/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.siu.application;

import com.siu.DAO.DOCGIA_DAO;
import com.siu.model.DOCGIA;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class Doc_gia extends javax.swing.JFrame {

    /**
     * Creates new form Doc_gia
     */
    private String msnvDN;
    public Doc_gia() throws Exception {
        initComponents();
        setLocationRelativeTo(null); // căn giữa form
        initTable();
    }
    public Doc_gia(String msnvDN) throws Exception {
        initComponents();
        setLocationRelativeTo(null); // căn giữa form
        initTable();
        this.msnvDN = msnvDN;
    }
    public String getMsnvDN() {
        return msnvDN;
    }
    DefaultTableModel model; // Mô hình dữ liệu cho JTable

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnTimKiem = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Độc giả");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MSDG", "Họ và tên", "Địa chỉ", "Ngày sinh", "Email", "Giới tính", "Ngày đăng kí", "Thông tin khác"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        btnTimKiem.setBackground(new java.awt.Color(51, 153, 255));
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(51, 153, 255));
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnCapNhat.setBackground(new java.awt.Color(51, 153, 255));
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(51, 153, 255));
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(51, 153, 255));
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ptit/icon/Graphicrating-Koloria-Button-Back.32.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initTable() throws Exception {
    // Tạo model cho JTable
    DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
    model.setRowCount(0);
    model.setColumnIdentifiers(new Object[]{
        "MSDG", "Họ và tên", "Địa chỉ", "Ngày sinh", "Email", "Giới tính", "Ngày đăng ký", "Nghề nghiệp"
    });

    // Lấy danh sách độc giả từ DAO
    DOCGIA_DAO dg_DAO = new DOCGIA_DAO();
    ArrayList<DOCGIA> lstDG = new ArrayList<>();
    lstDG = dg_DAO.getDSDG();
    // Định dạng ngày
    SimpleDateFormat dinhDang = new SimpleDateFormat("dd/MM/yyyy");

    // Duyệt danh sách độc giả và thêm vào bảng
    for (DOCGIA dg : lstDG) {
        String[] data = {
            dg.getMSDG(),
            dg.getTenDG(),
            dg.getDiaChi(),
            dinhDang.format(dg.getNgaySinh()),
            dg.getEmail(),
            dg.getGioiTinh(),
            dinhDang.format(dg.getNgayDK()),
            dg.getThongTinKhac()
        };
        System.out.println(dg);
        model.addRow(data);
    }

    // Gán model vào JTable
    jTable1.setModel(model);
}

    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
//        Menu menu = new Menu(msnvDN);
//        menu.setVisible(true);
//        menu.setLocationRelativeTo(this);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        this.setEnabled(false); // khóa form hiện tại
        Them_dg dg = new Them_dg();
        dg.setVisible(true);
//        this.dispose();
    
    // Khi form Them_nv đóng, mở lại form cha:
        dg.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            setEnabled(true);  // bật lại form cha
            toFront(); 
            try {
                initTable();// đưa form cha ra trước
            } catch (Exception ex) {
                Logger.getLogger(Nhan_vien.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    });
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) // ko chọn dòng nào 
        {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 đọc giả!");
            return;
        }
        // Lấy dữ liệu dòng đang chọn
        String msdg = jTable1.getValueAt(selectedRow, 0).toString();
        String hoTen = jTable1.getValueAt(selectedRow, 1).toString();
        String diaChi = jTable1.getValueAt(selectedRow, 2).toString();
        String ngaySinh = jTable1.getValueAt(selectedRow, 3).toString();
        String email = jTable1.getValueAt(selectedRow, 4).toString();
        String gioiTinh = jTable1.getValueAt(selectedRow, 5).toString();
        String ngayDK = jTable1.getValueAt(selectedRow, 6).toString();
        String thongTinKhac = jTable1.getValueAt(selectedRow, 7).toString();
        
        this.setEnabled(false); // khóa form hiện tại
        Cap_nhat_dg cnnv = new Cap_nhat_dg(msdg, hoTen, diaChi, ngaySinh, email, gioiTinh, ngayDK, thongTinKhac);
        cnnv.setVisible(true);
//        this.dispose();
    
    // Khi form Them_nv đóng, mở lại form cha:
        cnnv.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            setEnabled(true);  // bật lại form cha
            toFront(); 
            try {
                initTable();// đưa form cha ra trước
            } catch (Exception ex) {
                Logger.getLogger(Nhan_vien.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    });
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String keyword = JOptionPane.showInputDialog(this, "Nhập mã độc giả cần tìm:");
        boolean found = false;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 0).toString().equalsIgnoreCase(keyword)) {
                jTable1.setRowSelectionInterval(i, i);
                found = true;
                break;
            }
        }

        if (!found) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy độc giả có mã: " + keyword);
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) // ko chọn dòng nào 
        {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn đọc giả để xóa!");
            return;
        } else {
            Object[] options = {"Yes", "No"};

            int choice = JOptionPane.showOptionDialog(this, "Bạn có muốn xóa không", "Xóa dữ liệu", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]);

            if (choice == JOptionPane.YES_OPTION) {
                DOCGIA_DAO dg_DAO = new DOCGIA_DAO();
                String msdg = jTable1.getValueAt(selectedRow, 0).toString();
                try {
                    String mess = dg_DAO.xoaDG(msdg);
                    JOptionPane.showMessageDialog(this, mess);
                } catch (Exception ex) {
                    Logger.getLogger(Doc_gia.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    initTable();
                } catch (Exception ex) {
                    Logger.getLogger(Doc_gia.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        jTable1.clearSelection();
    }//GEN-LAST:event_btnClearActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        Menu menu = new Menu(msnvDN);
        menu.setVisible(true);
        menu.setLocationRelativeTo(this);
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doc_gia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doc_gia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doc_gia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doc_gia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Doc_gia().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Doc_gia.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
