/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.siu.application;

import com.siu.DAO.NHANVIEN_DAO;
import com.siu.model.NHANVIEN;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class Nhan_vien extends javax.swing.JFrame {

    /**
     *
     */
    private String msnvDN;
    public Nhan_vien() throws Exception {
        initComponents();
        setLocationRelativeTo(null); // căn giữa form
        initTable();
    }
    public Nhan_vien(String msnvDN) throws Exception {
        initComponents();
        setLocationRelativeTo(null); // căn giữa form
        initTable();
        this.msnvDN = msnvDN;
        // nếu cần load dữ liệu theo msnvDN
        // loadDataTheoUser(msnvDN);
    }

    // nếu code khác cần đọc
    public String getMsnvDN() {
        return msnvDN;
    }

    
    DefaultTableModel model; // Mô hình dữ liệu cho JTable

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nhân viên");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Họ và tên", "Địa chỉ", "Ngày sinh", "Giới tính", "Số điện thoại", "Email", "Ngày vào làm", "Chức vụ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setFillsViewportHeight(true);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ptit/icon/Graphicrating-Koloria-Button-Back.32.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(51, 153, 255));
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(51, 153, 255));
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnCapNhat.setBackground(new java.awt.Color(51, 153, 255));
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(51, 153, 255));
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnTimKiem.setBackground(new java.awt.Color(51, 153, 255));
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBack)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initTable() throws Exception {
        model = (DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        model.setColumnIdentifiers(new Object[]{
            "Mã nhân viên", "Họ và tên", "Địa chỉ", "Ngày sinh", "Giới tính", "Số điện thoại", "Email", "Ngày vào làm", "Chức vụ"
        });
        NHANVIEN_DAO nv_DAO = new NHANVIEN_DAO();
        ArrayList<NHANVIEN> lstNV = new ArrayList<>();
        
        lstNV = nv_DAO.getDSNV();
        SimpleDateFormat dinhDang = new SimpleDateFormat("dd/MM/yyyy");
        for (NHANVIEN nv :lstNV){
            String [] data = {nv.getMSNV(), nv.getHoTenNV(), nv.getDiaChiNV(),
                dinhDang.format(nv.getNgaySinhNV()), nv.getGioiTinh(),
                nv.getSdtNV(), nv.getEmailNV(),
                dinhDang.format(nv.getNgayVaoLam()), nv.getChucVu()};
            model.addRow(data);
        }
        
        
        jTable1.setModel(model);
    }
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
//        Menu menu = new Menu(msnvDN);
//        menu.setVisible(true);
//        menu.setLocationRelativeTo(this);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        this.setEnabled(false); // khóa form hiện tại
        Them_nv nv = new Them_nv();
        nv.setVisible(true);
//        this.dispose();
    
    // Khi form Them_nv đóng, mở lại form cha:
        nv.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            setEnabled(true);  // bật lại form cha
            toFront(); 
            try {
                initTable();// đưa form cha ra trước
            } catch (Exception ex) {
                Logger.getLogger(Nhan_vien.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    });
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) // ko chọn dòng nào 
        {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên để cập nhật!");
            return;
        }
        // Lấy dữ liệu dòng đang chọn
        String msnv = jTable1.getValueAt(selectedRow, 0).toString();
        String hoTen = jTable1.getValueAt(selectedRow, 1).toString();
        String diaChi = jTable1.getValueAt(selectedRow, 2).toString();
        String ngaySinh = jTable1.getValueAt(selectedRow, 3).toString();
        String gioiTinh = jTable1.getValueAt(selectedRow, 4).toString();
        String sdt = jTable1.getValueAt(selectedRow, 5).toString();
        String email = jTable1.getValueAt(selectedRow, 6).toString();
        String ngayVaoLam = jTable1.getValueAt(selectedRow, 7).toString();
        String chucVu = jTable1.getValueAt(selectedRow, 8).toString();
        
        this.setEnabled(false); // khóa form hiện tại
        Cap_nhat_nv cnnv = new Cap_nhat_nv(msnv, hoTen, diaChi, ngaySinh, gioiTinh, sdt, email, ngayVaoLam, chucVu);
        cnnv.setVisible(true);
//        this.dispose();
    
    // Khi form Them_nv đóng, mở lại form cha:
        cnnv.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            setEnabled(true);  // bật lại form cha
            toFront(); 
            try {
                initTable();// đưa form cha ra trước
            } catch (Exception ex) {
                Logger.getLogger(Nhan_vien.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    });
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String keyword = JOptionPane.showInputDialog(this, "Nhập mã nhân viên cần tìm:");
        boolean found = false;

        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 0).toString().equalsIgnoreCase(keyword)) {
                jTable1.setRowSelectionInterval(i, i);
                found = true;
                break;
            }
        }

        if (!found) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy nhân viên có mã: " + keyword);
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try {
            // TODO add your handling code here:
            Menu menu = new Menu(msnvDN);
            menu.setVisible(true);
            menu.setLocationRelativeTo(this);
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(Nhan_vien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        jTable1.clearSelection();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) // ko chọn dòng nào 
        {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên để xóa!");
            return;
        } else {
            Object[] options = {"Yes", "No"};

            int choice = JOptionPane.showOptionDialog(this, "Bạn có muốn xóa không", "Xóa dữ liệu", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]);

            if (choice == JOptionPane.YES_OPTION) {
                NHANVIEN_DAO nv = new NHANVIEN_DAO();
                String msnv = jTable1.getValueAt(selectedRow, 0).toString();
                try {
                    String mess = nv.xoaNV(msnv);
                    JOptionPane.showMessageDialog(this, mess);
                } catch (Exception ex) {
                    Logger.getLogger(Nhan_vien.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    initTable();
                } catch (Exception ex) {
                    Logger.getLogger(Nhan_vien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nhan_vien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nhan_vien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nhan_vien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nhan_vien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Nhan_vien().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Nhan_vien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
