/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.siu.application;

import com.siu.DAO.BAN_SAO_DAO;
import com.siu.DAO.DAU_SACH_DAO;
import com.siu.DAO.DICHVU_DAO;
import com.siu.DAO.DOCGIA_DAO;
import com.siu.model.BAN_SAO;
import com.siu.model.DAU_SACH;
import com.siu.model.DOCGIA;
import com.siu.model.PHIEUMUON;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class Sach extends javax.swing.JFrame {

    /**
     * Creates new form Sach
     */
    private String msnvDN;

    public Sach() {
        initComponents();
        loadTableDauSach();
    }

    public Sach(String msnvDN) {
        initComponents();
        loadTableDauSach();
        this.msnvDN = msnvDN;
    }

    private void warn(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Warning", JOptionPane.WARNING_MESSAGE);
    }

    public boolean isNumber(String text) {
        try {
            Integer.parseInt(text);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    // nếu code khác cần đọc
    public String getMsnvDN() {
        return msnvDN;
    }

    public void loadTableDauSach() {
        try {
//            tableDauSach.setModel(new javax.swing.table.DefaultTableModel(
//                    new Object[][]{},
//                    new String[]{
//                        "MaDauSach", "TenSach", "MaTacGia", "MSNXB", "MaLoaiSach", "NamXB", "LanXB", "TomTat"
//                    }));

            List<DAU_SACH> list = dao.getDauSach();

            DefaultTableModel tblModel = (DefaultTableModel) tableDauSach.getModel();

            tblModel.setRowCount(0);

            for (DAU_SACH ds : list) {
                Object[] row = new Object[]{
                    ds.getMaDauSach(),
                    ds.getTenSach(),
                    ds.getMaTacGia(),
                    ds.getmSNXB(),
                    ds.getMaLoaiSach(),
                    ds.getNamXB(),
                    ds.getLanXB(),
                    ds.getTomTat()
                };
                tblModel.addRow(row);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi tải dữ liệu: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogMuon = new javax.swing.JDialog();
        jPanel45 = new javax.swing.JPanel();
        jPanel46 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        muontxtSPM = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        muontxtMSDG = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        cbxHanNgay = new javax.swing.JComboBox<>();
        cbxHanThang = new javax.swing.JComboBox<>();
        txtHanNam = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        muonlistMBS = new javax.swing.JList<>();
        jLabel49 = new javax.swing.JLabel();
        jPanel48 = new javax.swing.JPanel();
        btnMuon = new javax.swing.JButton();
        btnHuyMuon = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDauSach = new javax.swing.JTable();
        btnTimKiem = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnMuonSach = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnThemBanSao = new javax.swing.JButton();
        btnChiTietSach = new javax.swing.JButton();

        dialogMuon.setTitle("Muon sach");
        dialogMuon.setMinimumSize(new java.awt.Dimension(654, 400));
        dialogMuon.setModal(true);
        dialogMuon.setResizable(false);
        dialogMuon.setSize(new java.awt.Dimension(641, 400));
        dialogMuon.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                dialogMuonWindowClosing(evt);
            }
        });
        dialogMuon.getContentPane().setLayout(null);

        jPanel45.setLayout(new java.awt.GridLayout(1, 0));

        jLabel40.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel40.setText("So PM");

        muontxtSPM.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        jLabel41.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel41.setText("MSDG");

        muontxtMSDG.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        jLabel48.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel48.setText("Han tra");

        cbxHanNgay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbxHanNgay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ngay", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cbxHanThang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbxHanThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thang", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        txtHanNam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtHanNam.setText("Nam");

        muonlistMBS.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        muonlistMBS.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane9.setViewportView(muonlistMBS);

        jLabel49.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel49.setText("Ma BS");

        javax.swing.GroupLayout jPanel46Layout = new javax.swing.GroupLayout(jPanel46);
        jPanel46.setLayout(jPanel46Layout);
        jPanel46Layout.setHorizontalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel46Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel46Layout.createSequentialGroup()
                        .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(muontxtSPM))
                    .addGroup(jPanel46Layout.createSequentialGroup()
                        .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(muontxtMSDG, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE))
                    .addGroup(jPanel46Layout.createSequentialGroup()
                        .addGroup(jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel46Layout.createSequentialGroup()
                                .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel46Layout.createSequentialGroup()
                                .addComponent(cbxHanNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(cbxHanThang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(txtHanNam, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel46Layout.setVerticalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel46Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(muontxtSPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(muontxtMSDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel48)
                    .addComponent(cbxHanNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxHanThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHanNam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel49))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel45.add(jPanel46);

        dialogMuon.getContentPane().add(jPanel45);
        jPanel45.setBounds(0, 0, 640, 260);

        jPanel48.setLayout(new java.awt.GridLayout(1, 0));

        btnMuon.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btnMuon.setText("Muon");
        btnMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuonActionPerformed(evt);
            }
        });
        jPanel48.add(btnMuon);

        btnHuyMuon.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btnHuyMuon.setText("Huy");
        btnHuyMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyMuonActionPerformed(evt);
            }
        });
        jPanel48.add(btnHuyMuon);

        dialogMuon.getContentPane().add(jPanel48);
        jPanel48.setBounds(0, 280, 640, 60);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sách");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        tableDauSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã đầu sách", "Tên sách", "Mã TG", "MSNXB", "Mã loại sách", "Năm XB", "Lần XB", "Tóm tắt"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableDauSach.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        tableDauSach.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(tableDauSach);

        btnTimKiem.setBackground(new java.awt.Color(51, 153, 255));
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(51, 153, 255));
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnCapNhat.setBackground(new java.awt.Color(51, 153, 255));
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnMuonSach.setBackground(new java.awt.Color(51, 153, 255));
        btnMuonSach.setForeground(new java.awt.Color(255, 255, 255));
        btnMuonSach.setText("Mượn sách");
        btnMuonSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuonSachActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(51, 153, 255));
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(51, 153, 255));
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ptit/icon/Graphicrating-Koloria-Button-Back.32.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnThemBanSao.setBackground(new java.awt.Color(51, 153, 255));
        btnThemBanSao.setForeground(new java.awt.Color(255, 255, 255));
        btnThemBanSao.setText("Thêm bản sao");
        btnThemBanSao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemBanSaoActionPerformed(evt);
            }
        });

        btnChiTietSach.setBackground(new java.awt.Color(51, 153, 255));
        btnChiTietSach.setForeground(new java.awt.Color(255, 255, 255));
        btnChiTietSach.setText("Chi tiết sách");
        btnChiTietSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietSachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnChiTietSach)
                .addGap(18, 18, 18)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnThemBanSao, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMuonSach, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1086, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemBanSao, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMuonSach, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChiTietSach, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
//        Menu menu = new Menu(msnvDN);
//        menu.setVisible(true);
//        menu.setLocationRelativeTo(this);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        this.setEnabled(false); // khóa form hiện tại
        Them_sach themsach = new Them_sach();
        themsach.setVisible(true);

        // Khi form Them_sach đóng, mở lại form cha và reload table:
        themsach.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                setEnabled(true);  // bật lại form cha
                toFront();         // đưa form cha ra trước
                loadTableDauSach(); // reload dữ liệu bảng
            }
        });
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnThemBanSaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemBanSaoActionPerformed
        int selectedRow = tableDauSach.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một đầu sách!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        // Lấy mã đầu sách từ dòng đang chọn
        String maDauSach = tableDauSach.getValueAt(selectedRow, 0).toString();

        // --- Tạo mã bản sao tự động ---
        BAN_SAO_DAO daoBS = new BAN_SAO_DAO();
        String maBanSao;

        try {
            List<BAN_SAO> list = daoBS.getByMaDauSach(maDauSach);
            int soLuong = list.size() + 1;   // số bản sao tiếp theo

            maBanSao = "BS-" + maDauSach + "-" + soLuong;

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi tạo mã bản sao: " + e.getMessage());
            return;
        }

        this.setEnabled(false);

        // Mở form thêm bản sao, truyền sẵn thông tin
        Them_ban_sao banSao = new Them_ban_sao(maBanSao, maDauSach);
        banSao.setVisible(true);

        banSao.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                setEnabled(true);
                toFront();
            }
        });
    }//GEN-LAST:event_btnThemBanSaoActionPerformed

    private void btnChiTietSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiTietSachActionPerformed
        int selectedRow = tableDauSach.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một đầu sách!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

// Lấy dữ liệu từ hàng được chọn
        String maDauSach = tableDauSach.getValueAt(selectedRow, 0).toString();
        String maTacGia = tableDauSach.getValueAt(selectedRow, 2).toString();
        String msNXB = tableDauSach.getValueAt(selectedRow, 3).toString();
        String maLoaiSach = tableDauSach.getValueAt(selectedRow, 4).toString();

// Khóa form cha
        this.setEnabled(false);

// Mở form chi tiết
        Chi_tiet_sach chiTiet = new Chi_tiet_sach(maDauSach, maTacGia, msNXB, maLoaiSach);
        chiTiet.setVisible(true);

// Khi đóng form chi tiết, mở lại form cha
        chiTiet.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                setEnabled(true);
                toFront();
            }
        });
    }//GEN-LAST:event_btnChiTietSachActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        int selectedRow = tableDauSach.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một đầu sách để cập nhật!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Lấy dữ liệu từ hàng được chọn
        String maDauSach = tableDauSach.getValueAt(selectedRow, 0).toString();
        String tenSach = tableDauSach.getValueAt(selectedRow, 1).toString();
        String maTacGia = tableDauSach.getValueAt(selectedRow, 2).toString();
        String msNXB = tableDauSach.getValueAt(selectedRow, 3).toString();
        String maLoaiSach = tableDauSach.getValueAt(selectedRow, 4).toString();
        String namXB = tableDauSach.getValueAt(selectedRow, 5).toString();
        String lanXB = tableDauSach.getValueAt(selectedRow, 6).toString();
        String tomTat = tableDauSach.getValueAt(selectedRow, 7).toString();

        // Mở form cập nhật và điền dữ liệu
        this.setEnabled(false); // khóa form cha
        Cap_nhat_sach capNhatForm = new Cap_nhat_sach(maDauSach, tenSach, maTacGia, msNXB, maLoaiSach, namXB, lanXB, tomTat);
        capNhatForm.setVisible(true);

        // Khi đóng form cập nhật, mở lại form cha và reload bảng
        capNhatForm.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                setEnabled(true);
                toFront();
                loadTableDauSach(); // reload dữ liệu
            }
        });
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnMuonSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuonSachActionPerformed

        int[] selectedRows = tableDauSach.getSelectedRows();

        if (selectedRows.length < 1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn đầu sách để mượn!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        DICHVU_DAO daoDV = new DICHVU_DAO();
        DefaultListModel modelMS;

        if (muonlistMBS.getModel() instanceof DefaultListModel) {
            modelMS = (DefaultListModel) muonlistMBS.getModel();
        } else {
            modelMS = new DefaultListModel();
            muonlistMBS.setModel(modelMS);
        }
        for (int row : selectedRows) {
            String mbs = "";
            try {
                mbs = daoDV.getMBS_CS(tableDauSach.getValueAt(row, 0).toString());

            } catch (Exception ex) {
                Logger.getLogger(Sach.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (mbs == null || mbs.trim().isEmpty()) {
                warn("Da het sach " + tableDauSach.getValueAt(row, 0).toString());
                return;

            }
            modelMS.addElement(mbs);
        }

        muonlistMBS.setModel(modelMS);
        dialogMuon.pack();
        dialogMuon.setLocationRelativeTo(this);
        dialogMuon.setVisible(true);
    }//GEN-LAST:event_btnMuonSachActionPerformed

    private DAU_SACH_DAO dao = new DAU_SACH_DAO();

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        try {
            String keyword = JOptionPane.showInputDialog(this,
                    "Nhập tên sách hoặc từ khóa cần tìm:",
                    "Tìm kiếm sách",
                    JOptionPane.QUESTION_MESSAGE);

            // Nếu người dùng bấm Cancel → thoát không làm gì
            if (keyword == null) {
                return;
            }

            keyword = keyword.trim();

            // Nếu keyword rỗng → load lại toàn bộ dữ liệu
            if (keyword.isEmpty()) {
                loadTableDauSach();
                JOptionPane.showMessageDialog(this,
                        "Đã tải lại tất cả đầu sách!",
                        "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            // Tìm kiếm
            List<DAU_SACH> list = dao.search(keyword);

            if (list.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Không tìm thấy sách nào phù hợp!",
                        "Kết quả", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            // Đổ kết quả tìm kiếm vào bảng
            DefaultTableModel model = (DefaultTableModel) tableDauSach.getModel();
            model.setRowCount(0);

            for (DAU_SACH d : list) {
                model.addRow(new Object[]{
                    d.getMaDauSach(),
                    d.getTenSach(),
                    d.getMaTacGia(),
                    d.getmSNXB(),
                    d.getMaLoaiSach(),
                    d.getNamXB(),
                    d.getLanXB(),
                    d.getTomTat()
                });
            }

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Lỗi tìm kiếm: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        tableDauSach.clearSelection();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableDauSach.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một đầu sách để xóa!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String maDauSach = tableDauSach.getValueAt(selectedRow, 0).toString();

        int confirm = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc chắn muốn xóa đầu sách này không?",
                "Xác nhận xóa",
                JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            boolean success = dao.deleteNangCao(maDauSach);

            if (success) {
                JOptionPane.showMessageDialog(this,
                        "Xóa đầu sách và các bản sao thành công!",
                        "Thông báo",
                        JOptionPane.INFORMATION_MESSAGE);
                loadTableDauSach();
            } else {
                JOptionPane.showMessageDialog(this,
                        "Không thể xóa vì còn bản sao đang được mượn!",
                        "Lỗi",
                        JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Lỗi khi xóa: " + e.getMessage(),
                    "Lỗi",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuonActionPerformed
        // TODO add your handling code here:
        String soPM = muontxtSPM.getText().trim();
        String msdg = muontxtMSDG.getText().trim();
        String msnv = msnvDN.trim();
        Date now = new Date();
        Date hanTra = null;
        String trangThai = "Dang muon";
        ArrayList<String> lstmbs = new ArrayList<>();

        DefaultListModel model;
        if (muonlistMBS.getModel() instanceof DefaultListModel) {
            model = (DefaultListModel) muonlistMBS.getModel();
        } else {
            model = new DefaultListModel();
            muonlistMBS.setModel(model);
        }

        for (int i = 0; i < model.getSize(); i++) {
            lstmbs.add(model.getElementAt(i).toString());
        }

        if (lstmbs.isEmpty()) {
            warn("Danh sach ma ban sao khong duoc de trong!");
            return;
        }

        if (soPM == null || soPM.isEmpty()) {
            warn("So phieu muon khong duoc de trong!");
            return;
        } else {
            DICHVU_DAO tmp = new DICHVU_DAO();
            try {
                PHIEUMUON pm = tmp.tkPhieumuon(soPM);
                if (pm == null) {
                } else {
                    warn("So phieu muon da ton tai!");
                    return;
                }
            } catch (Exception ex) {
                Logger.getLogger(Sach.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (msdg == null || msdg.isEmpty()) {
            warn("Ma so doc gia khong duoc de trong!");
            return;
        } else {
            DOCGIA_DAO dao = new DOCGIA_DAO();
            DOCGIA dg;
            try {
                dg = dao.tkBangMSDG(msdg);
                if (dg == null) {
                    warn("Ma so doc gia khong ton tai!");
                    return;
                }
            } catch (Exception ex) {
                Logger.getLogger(Sach.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        if (msnv == null || msnv.isEmpty() || msnvDN == null || msnvDN.trim().isEmpty()) {
            warn("Ma so nhan vien khong duoc de trong!");
            return;
        }
        if (cbxHanNgay.getSelectedIndex() == 0 || cbxHanThang.getSelectedIndex() == 0 || !isNumber(txtHanNam.getText())) {
            warn("Ngay thang nam han tra khong hop le!");
            return;
        } else {
            int nam = Integer.parseInt(txtHanNam.getText());

            hanTra = new Date(nam - 1900, Integer.parseInt(cbxHanThang.getSelectedItem().toString()) - 1, Integer.parseInt(cbxHanNgay.getSelectedItem().toString()));
            if (hanTra.before(now)) {
                warn("Han tra khong hop le!");
                return;
            }
        }
        DICHVU_DAO dao = new DICHVU_DAO();

        try {
            String messTPM = dao.themPhieuMuon(soPM, msdg, msnv, now, hanTra, trangThai);
            if (!messTPM.equalsIgnoreCase("Them phieu muon thanh cong!")) {

                JOptionPane.showMessageDialog(this, messTPM);
                return;
            }
        } catch (Exception ex) {
            Logger.getLogger(Sach.class.getName()).log(Level.SEVERE, null, ex);
        }
        PHIEUMUON pm = null;
        try {
            pm = dao.tkPhieumuon(soPM);
        } catch (Exception ex) {
            Logger.getLogger(Sach.class.getName()).log(Level.SEVERE, null, ex);
        }
        boolean ktra = false;
        try {
            String messTCT = dao.muonSach(pm, lstmbs);
            if (messTCT.equalsIgnoreCase("Muon thanh cong!")) {
                ktra = true;
            }
            JOptionPane.showMessageDialog(this, messTCT);

        } catch (Exception ex) {
            Logger.getLogger(Sach.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (ktra) {
            muontxtSPM.setText("");
            muontxtMSDG.setText("");
            cbxHanNgay.setSelectedIndex(0);
            cbxHanThang.setSelectedIndex(0);
            txtHanNam.setText("Nam");
            muonlistMBS.setModel(new DefaultListModel<>());
            tableDauSach.clearSelection();
        }
    }//GEN-LAST:event_btnMuonActionPerformed

    private void btnHuyMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyMuonActionPerformed
        // TODO add your handling code here:
        dialogMuon.dispose();
        muontxtSPM.setText("");
        muontxtMSDG.setText("");
        cbxHanNgay.setSelectedIndex(0);
        cbxHanThang.setSelectedIndex(0);
        txtHanNam.setText("Nam");
        muonlistMBS.setModel(new DefaultListModel<>());
        tableDauSach.clearSelection();
    }//GEN-LAST:event_btnHuyMuonActionPerformed

    private void dialogMuonWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dialogMuonWindowClosing
        // TODO add your handling code here:
        dialogMuon.dispose();
        muontxtSPM.setText("");
        muontxtMSDG.setText("");
        cbxHanNgay.setSelectedIndex(0);
        cbxHanThang.setSelectedIndex(0);
        txtHanNam.setText("Nam");
        muonlistMBS.setModel(new DefaultListModel<>());
        tableDauSach.clearSelection();
    }//GEN-LAST:event_dialogMuonWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:Menu menu = new Menu(msnvDN);
        Menu menu = new Menu(msnvDN);
        menu.setVisible(true);
        menu.setLocationRelativeTo(this);
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sach("Test").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnChiTietSach;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHuyMuon;
    private javax.swing.JButton btnMuon;
    private javax.swing.JButton btnMuonSach;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemBanSao;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbxHanNgay;
    private javax.swing.JComboBox<String> cbxHanThang;
    private javax.swing.JDialog dialogMuon;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JList<String> muonlistMBS;
    private javax.swing.JTextField muontxtMSDG;
    private javax.swing.JTextField muontxtSPM;
    private javax.swing.JTable tableDauSach;
    private javax.swing.JTextField txtHanNam;
    // End of variables declaration//GEN-END:variables
}
